stages:
  - build
  - test

build:
  image: python:3.10.12
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y gfortran build-essential
    - pip install numpy
  script:
    - chmod +x ./src/fortran/run.sh
    - ./src/fortran/run.sh
  artifacts:
    paths:
      - "*.so"

test:
  image: python:3.10.12
  stage: test
  dependencies:
    - build
  variables:
    PYTHONPATH: "."
  before_script:
    - pip install pytest numpy scipy matplotlib numba
  script:
    - pytest -s
